### ISSUE TITLE
Clean up your code

### ISSUE THREAD

**Issue by Razpudding** [Sidstumple/cmd-touch#9]
Some files read like they were stolen from a tutorial...
https://github.com/Sidstumple/cmd-touch/blob/master/routes/index.js
Reference the source and remove unnecessary code comments.

**Comment by Razpudding** [comment]
There's a lot of dead code in a lot of your files

**Comment by Sidstumple** [comment]
That's what Keystone does; it adds all the files you need and you can choose to add extra code comments, which I obviously did. 

I'll walk through all files and remove unnecessary code.
